baseURL = 'https://romanfedoruk.com'
languageCode = 'en-us'
title = 'Roman Fedoruk Portfolio'
theme = 'PaperMod'

[minify]
    disableXML = true
    minifyOutput = true

[params]
    [params.homeInfoParams]
        enabled = true
        title = "<Title>"
    [blackfriday]
      plainIDAnchors = true
      hrefTargetBlank = true
